### ISSUE TITLE
Opening the file

### ISSUE THREAD

**Issue by ghost** [Ved-programmer/Run-Time-Visualizer#34]
# Hi Ved,

Now whenever you need to run this program, we had to open paste the file path and move the file to be checked into the same directory, but what if the file is too big ? it also causes a bit of some inconvenience in always moving the file, so if we keep an option on top of the application, like as shown below....

![Screenshot 2021-04-21 193231](https://user-images.githubusercontent.com/81476559/115568060-8b15d980-a2d9-11eb-98f5-95a4d38f7484.png)

Wouldn't it be great, cause this save a lot of time, even though moving a file from one directory to another doesn't take much time, what may we know, sometime the file might have to depend on other files as module dependencies, and I know that tkinter has such an option where the top menu bar would have it's sub-options.

Good Luck !

Regards,
Navdeep.

**Comment by Ved-programmer** [comment]
I get your point, however, this wouldn't be allowed by the timathon code jam. So I Shouldn't make this change. So I am closing this issue
